services:
  IssueTrackerDb:
    container_name: IssueTrackerDb
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd123"
    ports:
      - "1433:1433"
    volumes:
      - my-volume:/var/opt/mssql

volumes:
  my-volume:
